language: python
python:
  - "3.7"
  - "3.8"
addons:
    apt:
        packages:
            - libfreetype6-dev
            - hdf5-tools
            - libhdf5-dev
            - libopenblas-dev
install:
  - pip install -e .
  - pip install -U pytest
services:
  - xvfb
script: pytest
